version: '2'

services:
  front-end:
    image: neotysdevopsdemo/front-end:DEV-0.1
    hostname: front-end
    restart: always
    cap_drop:
    - all
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=front-end environment=dev
  edge-router:
    image: neotysdevopsdemo/edge-router:0.1
    ports:
    - '80:80'
    - '8080:8080'
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    - CHOWN
    - SETGID
    - SETUID
    - DAC_OVERRIDE
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=edge-router environment=dev
    tmpfs:
    - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
  catalogue:
    image: neotysdevopsdemo/catalogue:DEV-VERSION_TO_REPLACE
    hostname: catalogue
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=catalogue environment=dev
  catalogue-db:
    image: neotysdevopsdemo/catalogue-db:DEV-VERSION_TO_REPLACE
    hostname: catalogue-db
    restart: always
    environment:
    - DT_CUSTOM_PROP=app=catalogue-db environment=dev
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_DATABASE=socksdb
  carts:
    image: neotysdevopsdemo/carts:DEV-VERSION_TO_REPLACE
    hostname: carts
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    - DT_CUSTOM_PROP=app=carts environment=dev
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    restart: always
    cap_drop:
    - all
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=carts-db environment=dev
    tmpfs:
    - /tmp:rw,noexec,nosuid
  orders:
    image: neotysdevopsdemo/orders:DEV-VERSION_TO_REPLACE
    hostname: orders
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    - DT_CUSTOM_PROP=app=orders environment=dev
  orders-db:
    image: mongo:3.4
    hostname: orders-db
    restart: always
    cap_drop:
    - all
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=orders-db environment=dev
    tmpfs:
    - /tmp:rw,noexec,nosuid
  shipping:
    image: neotysdevopsdemo/shipping:DEV-VERSION_TO_REPLACE
    hostname: shipping
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
    environment:
    - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    - DT_CUSTOM_PROP=app=shipping environment=dev
  queue-master:
    image: neotysdevopsdemo/queue-master:DEV-VERSION_TO_REPLACE
    hostname: queue-master
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    environment:
    - DT_CUSTOM_PROP=app=queue-master environment=dev
    tmpfs:
    - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    restart: always
    cap_drop:
    - all
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    - DAC_OVERRIDE
    read_only: true
  payment:
    image: neotysdevopsdemo/payment:DEV-VERSION_TO_REPLACE
    hostname: payment
    restart: always
    cap_drop:
    - all
    environment:
    - DT_CUSTOM_PROP=app=payment environment=dev
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
  user:
    image: neotysdevopsdemo/user:DEV-VERSION_TO_REPLACE
    hostname: user
    restart: always
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    environment:
    - MONGO_HOST=user-db:27017
    - DT_CUSTOM_PROP=app=user environment=dev
  user-db:
    image: neotysdevopsdemo/user-db:DEV-VERSION_TO_REPLACE
    hostname: user-db
    restart: always
    cap_drop:
    - all
    cap_add:
    - CHOWN
    - SETGID
    - SETUID
    environment:
    - DT_CUSTOM_PROP=app=user-db environment=dev
    read_only: true
    tmpfs:
    - /tmp:rw,noexec,nosuid
networks:
  default:
    external:
      name: parasoft